[package]
name = "apicize_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apicize_lib = { path = "../lib", version = "0.1.0" }
serde_json = "1.0.110"
tokio = "1.35.1"
