services:
  api:
    build: 
       context: .
       dockerfile: ./Dockerfile
    networks:
      - local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8080:8080"
    
networks:
  local:
    driver: bridge